name: GitHub Code Quality Check Demo
on: workflow_dispatch
jobs:
  pylint-runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.11.1
        pip install pyspark
    - name: Run Pylint
      run: |
        python lint.py --path ./adb-root --threshold 2
