name: GitHub Code Quality Check Demo
on: workflow_dispatch
jobs:
  pylint-runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.11.1
        pip install -U databricks-connect==9.1.*
    - name: Configure DBConnect
      run: |
        echo "y
        https://adb-22850018007398.18.azuredatabricks.net
        dapi81939f12e08e245c7bb4a21c67990e64-3
        0320-194318-gourulnl
        22850018007398
        8787" | databricks-connect configure
    - name: Run Pylint
      run: |
        python lint.py --path ./adb-root --threshold 2
