name: GitHub Actions Artifact  Demo
on: workflow_dispatch
jobs:
  Download-GitHub-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
             workflow: github-actions-demo.yml
             workflow_conclusion: success
             branch: dev
             run_number: 20
             
             
      
